### ISSUE TITLE
Pass check.names to data.frame

### ISSUE THREAD

**Issue by holstius** [renkun-ken/formattable#1]
I'd suggest `check.names = FALSE` in the call to `data.frame` in the body of `formattable.data.frame`. (Otherwise, spaces in the column names get clobbered.)

Great package!!!

**Comment by renkun-ken** [comment]
Thanks for the suggestion! I'm currently working on `format-number` branch. I'll take a look at this.

**Comment by renkun-ken** [comment]
The commit to `master` should work for you. `check.names` is `FALSE` by default to limit the behavior of the formatting function to only formatting rather than altering anything else. Does that work for you?
