### ISSUE TITLE
Way to display diverging color scheme in table?

### ISSUE THREAD

**Issue by kiefersmith** [renkun-ken/formattable#102]
I'm trying to display a percent difference column in a table that would display red for positive values and green for negative values.  Is there any way to pass a gradient from green to transparent to red?  I see that gradient returns a matrix, which I could create manually, but how would that interface with color_tile?  Any guidance would be appreciated.  Thank you!

**Comment by dward88** [comment]
I've had some success with the following: 

```{r }
library(dplyr)
library(kableExtra)
library(formattable)

x = currency(c(1000000,
                 -3000,
                400000,
                800000,
                 -1700,
                     0,
                 50000))

x = ifelse(
  x <= 0.0, 
  color_tile("light blue", "transparent")(x*c(x<=0)),
  color_tile("transparent", "pink")(x*c(x>=0)))

x %>% 
  kable(escape = F) %>% 
  kable_styling(bootstrap_options = c("striped", "hover"), 
                full_width = F)
```
Which gives the following:

<img src="https://user-images.githubusercontent.com/14680769/43362539-e31579cc-932f-11e8-98fb-86659000bc6e.png" width="110" height="279">

It would take a couple of additional steps to get the negative and positive color scales to be normalised. 

At the moment, you can see that the blue scale is showing the _most negative_ value as `"light blue"`. On a balanced scale, all of the negative values here would be very close to `"transparent"`.
