### ISSUE TITLE
Formattable scales package conflict "Error in is.finite(x)"...

### ISSUE THREAD

**Issue by vp3** [renkun-ken/formattable#122]
When packages "Formattable" and "Scales" are loaded at the same time I receive an "Error in is.finite(x)" error when running code using the formattable function. 
Unloading the "Scales" package fixes this error and allows "Formattable" to operating normally. 
I am using RStudio Open Server Version 1.2.1335 running on Ubuntu 16.04 with rbase 3.5 something. I haven't upgraded to 3.6 yet. 
'scales' version 1.0.0
'formattable' version 0.2.0.1
The code is in a long rmd file. Formattable is used earlier and scales is used lower down the script in a different chunk. Formattable and scales were originally loaded at the beginning of the document and that caused the conflict.
My work around is to load scales only when needed later on in the script and then unload. 
library(scales) at the beginning of that chunk (with messages suppressed using message=FALSE in the chunk setup)
detach(package:scales) to unload the scales package at the end of the chunk.
This works for me so no response needed. Just thought you should know and others may benefit from this info.

**Comment by renkun-ken** [comment]
There are unfortunately some name conflicts of functions in formattable and scales. If you only use a small subset of functions in scales, I suggest you use `scales::` to point to functions in scales.

**Comment by vp3** [comment]
Good suggestion. I'll use it. Thx!
