### ISSUE TITLE
[Request] Ability to add header/footers

### ISSUE THREAD

**Issue by chillywings** [renkun-ken/formattable#125]
This is a nice package, however I'm struggling to implement it as I'm unable to add a simple title to my table. It appears people are integrating the color_tile/color_bar functionality with kable, however this wouldn't be as necessary if the package could add some simple things like titles. It would really round things out.

**Comment by renkun-ken** [comment]
You may try

```r
formattable::formattable(mtcars, caption = "mtcars")
```

**Comment by chillywings** [comment]
That worked! Thanks. I searched the CRAN documentation and some other sources and didn't see this option anywhere.
