### ISSUE TITLE
formattable.data.frame could allow to label columns nicely

### ISSUE THREAD

**Issue by jangorecki** [renkun-ken/formattable#127]
It would be very convinient if formattable had a feature for columns labelling on the html output.
Then there is no need to rename columns on data.frame but just pass a vector of new names to `formattable()`. New names is a visual layer of the data, so it doesn't really fit to renaming that on R's data.frame, during formatting it seems to be more appropriate.
Below a suggestion of a API for requested feature.
```r
library(formattable)
d = data.frame(in_n=1:2, out_n=1:2, seconds=1:2, delta=1:2/100)
pretty_names = c("Input size","Output size","Time seconds","Time \u2206")
formattable(d, colnames=pretty_names)
```

**Comment by renkun-ken** [comment]
`formattable.data.frame` ultimately calls `knitr::kable()` to perform the conversion from data.frame to HTML. In fact, `kable(col.names = character())` can be used to do this. For example,

```r
d = data.frame(v1=percent(rnorm(10, 0, 0.1)))
formattable(d, col.names = c("Input size"))
```

**Comment by jangorecki** [comment]
@renkun-ken cool! thanks for checking that out, I can confirm it also works for unicode
```r
library(formattable)
d = data.frame(in_n=1:2, out_n=1:2, seconds=1:2, delta=1:2/100)
pretty_names = c("Input size","Output size","Time seconds","Time \u2206")
formattable(d, col.names=pretty_names)
```
maybe worth documenting that somewhere?

**Comment by renkun-ken** [comment]
Yes, I'll add more docs when I have time.
