### ISSUE TITLE
Retire Travis and AppVeyor

### ISSUE THREAD

**Issue by krlmlr** [renkun-ken/formattable#140]
Now we have GitHub actions, Travis and AppVeyor only slows down the checks for a branch without adding real value it seems. Would you like to deactivate these services for this repo? We can delete the `.yml` files afterwards.

**Comment by krlmlr** [comment]
We also should add a GitHub badge then.

**Comment by renkun-ken** [comment]
Definitely. Feel free to make changes for this.

**Comment by krlmlr** [comment]
I can do that, but cant' deactivate Travis and AppVeyor. Do you prefer keeping them on?

**Comment by renkun-ken** [comment]
With GitHub actions, we don't really need Travis and AppVeyor any more. I'd rather disable them to save some energy 😸

**Comment by renkun-ken** [comment]
OK, both Travis and AppVeyor are disabled.

**Comment by krlmlr** [comment]
Thanks!
