### ISSUE TITLE
No formatted table produced

### ISSUE THREAD

**Issue by doethwr** [renkun-ken/formattable#162]
Using formattable from R Studio:
myTable <- table(myData$geschl, myData$schultyp)
myTable

     1  2  3
  m 44 48 38
  w 52 49 32

formattable(myTable)

     1  2  3
  m 44 48 38
  w 52 49 32

with no output in the viewer. Solution?

**Comment by renkun-ken** [comment]
`table` is essentially a `matrix`. Currently, we don't render matrix as a htmlwidget by default because there are e.g. percent matrix. We only render `data.frame`.

In your case, you might need to run the following as a work-around:

```r
formattable(as.data.frame(unclass(myTable)))
```

**Comment by doethwr** [comment]
Thank you! I’ll try that.
I had changed the matrix to data.frame, but didn’t unclass.



Kun Ren ***@***.***> schrieb am Sa. 18. Dez. 2021 um 15:54:

**Comment by doethwr** [comment]
Your solution worked worked. Thanks again
