### ISSUE TITLE
getting error in is.finite(x)

### ISSUE THREAD

**Issue by timelyportfolio** [renkun-ken/formattable#18]
I think this is a conflict with `df` from another package.

For some reason, I get this now.  Can you check to see if you might also be having this problem?  I'll keep digging for a solution.

```
Error in is.finite(x) : default method not implemented for type 'closure'
In addition: Warning message:
In formatC(function (x, df1, df2, ncp, log = FALSE)  :
  class of 'x' was discarded
```

**Comment by renkun-ken** [comment]
I don't quite get the point? Would you please make a reproducible example?

**Comment by timelyportfolio** [comment]
No point except I screwed up, so I closed.  Sorry.

**Comment by renkun-ken** [comment]
:)
