### ISSUE TITLE
make formattable also works as an htmlwidget

### ISSUE THREAD

**Issue by timelyportfolio** [renkun-ken/formattable#3]
Explore different ways to allow `formattable` to work as an `htmlwidget`.  Currently, `formattable` only works when in the context of a `rmarkdown` document.  Adding `htmlwidget` functionality would allow it to work in other contexts such as console, RStudio Viewer, and Shiny.

**Comment by renkun-ken** [comment]
Yes, that's exactly what I want. But I'm not quite familiar with `htmlwidget`. PRs are sincerely welcomed! I'll also take a look at how it works :)

**Comment by timelyportfolio** [comment]
Ok, I think I can put something together fairly quickly to give us a headstart.

**Comment by timelyportfolio** [comment]
Would you want to do something like `as.htmlwidget`?  Up for any name you would like.

Do you want the markdown conversion to happen on the `R` side or the JavaScript side?  Or does it even matter?

**Comment by renkun-ken** [comment]
I think it should work like in interactive mode, I can preview my `formattable data.frame` as a `htmlwidget` in Viewer pane in RStudio, and in rmarkdown document the object is printed as markdown table and rendered as a simple html table with cell styles as supposed. It should not introduce additional js libraries required to render a rmd, or has it?

I'm not sure about the difference between R side conversion and js-side. I'll appreciate it if you can make some gist to show a simple demo :)

**Comment by timelyportfolio** [comment]
I'll put something together in a forked branch as a first draft.

**Comment by timelyportfolio** [comment]
Well, dang it looks like the `markdown` package does not fully support tables in your produced markdown.  I'm going to try it on the `JavaScript` side.

**Comment by timelyportfolio** [comment]
Will require further testing, but here is a very quick example, but unfortunately it doesn't work fully on the example in `Readme.Rmd`.  You can test it by

```
devtools::install_github("timelyportfolio/formattable@feature/htmlwidget")

library(formattable)

as_htmlwidget(
  formattable(mtcars)
)
# here is where you'll see the problem
as_htmlwidget(
  formattable(df, list(
    age = color_tile("white", "orange"),
    grade = formatter("span",
                      style = x ~ ifelse(x == "A", style(color = "green", font.weight = "bold"), NA)),
    test1_score = color_bar("pink", 0.2),
    test2_score = color_bar("pink", 0.2),
    final_score = formatter("span",
                            style = x ~ style(color = ifelse(rank(-x) <= 3, "green", "gray")),
                            x ~ sprintf("%.2f (rank: %02d)", x, rank(-x))),
    registered = formatter("span", 
                           style = x ~ style(color = ifelse(x, "green", "red")),
                           x ~ icontext(ifelse(x, "ok", "remove"), ifelse(x, "Yes", "No")))
  ))
)
```

Auto-sizing will also probably be tricky, but can be handled.

**Comment by timelyportfolio** [comment]
I also did not include `jQuery` for now, so there will be an error in the browser console.

**Comment by renkun-ken** [comment]
Thanks! I tried the forked branch with the following code

```r
as_htmlwidget(formattable(mtcars, list(mpg = color_tile("white", "orange"))))
``` 

and it works.

For the example in `README.Rmd`, `df` has to be defined. I tried the example and the output is a mess.

**Comment by timelyportfolio** [comment]
Right, and without looking deeply, you'll see the `|` and `||` separators not correctly parsed by the `markdown` package in R.  I tried `markdown-js` but it didn't treat correctly either, so I'm searching for a markdown renderer that correctly handles pandoc's special markdown flavor.

**Comment by timelyportfolio** [comment]
actually, it might just be the `\n` that is causing the trouble.

**Comment by timelyportfolio** [comment]
It was the `\n`.  If I `gsub` to replace, I get a much better result.  If possible, can you reinstall the forked version and test it.

On a separate issue, I wonder if we should just leverage Shiny's Bootstrap dependencies for the dependencies.

**Comment by renkun-ken** [comment]
Cool, the table looks much better now :) Let's try a bootstrap to make it look like what appears in the rmd.

**Comment by timelyportfolio** [comment]
In regards to using the `shiny` Bootstrap helper `bootstrapPage`, I just pushed the changes to show how it might work.  

### positive
1. do not need to worry with handling the Bootstrap dependencies
2. do not need to update Bootstrap down the road
3. avoid future unforeseen conflicts with `shiny` or other `htmlwidgets`
4. much smaller package since do not need JS/CSS dependencies

### negative
1. dependency on `shiny`.  We can alleviate this by using `Suggest` rather than `Imports`, but of course this is not a perfect solution.

**Comment by timelyportfolio** [comment]
I just pushed a changed `Readme.Rmd` to see how the `htmlwidget` works in `rmarkdown` context.  I'll play with style/sizing.

**Comment by timelyportfolio** [comment]
styling is fixed and I added an example in https://github.com/timelyportfolio/formattable/commit/aa819be46931ef96af6ede7cfc2586162d590d00

**Comment by renkun-ken** [comment]
That's really neat! I wonder if it is possible or right to automatically create a htmlwidget in interactive mode but prints its markdown representation in rendering rmd?

**Comment by timelyportfolio** [comment]
Is this as easy as adding a check for `interactive() == TRUE` in the `print.formattable` and if so calling the htmlwidget conversion function instead of the `do.call`?

**Comment by renkun-ken** [comment]
Yes, it solves the problem. One more minor problem: `knitr::kable` supports producing pandoc output which supports table caption but markdown output seems to always omit caption. Is there a way to support table caption somehow?

**Comment by renkun-ken** [comment]
If you feel sure about the implementation, would you please send a PR of the feature branch?

**Comment by timelyportfolio** [comment]
This simple [change](https://github.com/timelyportfolio/formattable/blob/40cc5fd321ce8b42cb1b4d499a748e51ad49a7b3/R/formattable.R#L171-L178) seems to work, but I'll admit I am a little out of my comfort zone here, so I am not sure of other side effects.

`interactive() == TRUE`  when in RStudio/console.  `interactive() == FALSE` when knitting/converting Rmd.  If you knit `Readme.Rmd`, you can see the difference.

**Comment by renkun-ken** [comment]
Would you mind if I add you as a collaborator to work on this feature?

**Comment by timelyportfolio** [comment]
Don't mind at all but certainly not necessary. Just let me know what works best.

**Comment by renkun-ken** [comment]
Great, I've just added you as a collaborator. Please create a branch in this repo and send a PR from your fork to the feature branch here.

**Comment by timelyportfolio** [comment]
Ok, any naming scheme for the branch, or is `feature/htmlwidget` ok?

**Comment by renkun-ken** [comment]
Yes, it's perfectly ok.

**Comment by timelyportfolio** [comment]
Ok, once travis confirms ready, I'll accept the pull.  Thanks.

**Comment by renkun-ken** [comment]
The feature now works fine.
