### ISSUE TITLE
[Question] How to adjust format AND change style in the meanwhile?

### ISSUE THREAD

**Issue by happyshows** [renkun-ken/formattable#32]
for example, I have a column called rate, it comes in 0.xx format.

On one hand, I want to style it as colored bar chart using the formatter(style) function.
On the other hand, I'd like to change the text to xx%

Could you provide a minimal example on how to achieve this?

Thanks.

**Comment by renkun-ken** [comment]
There are two solutions available at the moment.

1. Convert the column in data frame to `percent`:

```r
library(formattable)

set.seed(100)
x <- data.frame(rate = percent(rnorm(20, 0.4, 0.05)))
formattable(x, list(rate = color_bar("lightpink", 0.2)))
```

2. Use `formatter` to create a formatter with customized text transformer.

```r
set.seed(100)
x <- data.frame(rate = rnorm(20, 0.4, 0.05))
formattable(x, list(rate = formatter("span",
    style = function(x) style(
      display = "block",
      width = percent(normalize(x, 0.2)),
      "border-radius" = "4px",
      "padding-right" = "4px",
      "background-color" = csscolor("lightpink")
    ), function(x) percent(x))))
```

Note that `formatter("span", style = function(x) style(display = "block"), function(x) percent(x))` will transform a column to `<span style="display: block">11.05%</span>`.
