### ISSUE TITLE
percent(NA) gives error

### ISSUE THREAD

**Issue by gluc** [renkun-ken/formattable#35]
Thanks for the fantastic package! I have wanted something like this for a long time.

Small issue (on the CRAN version): `percent(NA)` gives an error: `Error during wrapup: no applicable method for 'percent' applied to an object of class "logical"`

However, `percent(as.numeric(NA))` does work.

Workaround: `formattalbe:::percent.numeric(NA)`

**Comment by renkun-ken** [comment]
The latest version should work for you now. Thanks for reporting!
