### ISSUE TITLE
Question: Is it possible to format by row (instead of by column)

### ISSUE THREAD

**Issue by gluc** [renkun-ken/formattable#36]
I realize that this is not the standard use case. But I would like to display a matrix of weights with, say, color_tile, but the color should be chosen as a function of the row values.

**Comment by shrektan** [comment]
I wound like to proposal the same feature. Sometimes reports would be better if were formatted by row.

**Comment by renkun-ken** [comment]
Thanks for posting the feature request. I'll consider this in detail.

**Comment by gluc** [comment]
In the meantime: I have an example how to calculate the colors by ourselves: https://github.com/gluc/ahp/blob/master/R/table.R#L43 

Result is here: 
![ahp](https://cloud.githubusercontent.com/assets/626832/12880029/0164f936-ce3c-11e5-95af-6c3c71638f70.png)

Or, live: http://ipub.com/apps/ahp

**Comment by jemus42** [comment]
I would also like to have the ability for row-wise formatting. That would be useful for many cases, like comparing similar variables and highlighting the min/max or something.

**Comment by MarauderPixie** [comment]
Just here to +1 this request.

**Comment by renkun-ken** [comment]
In v0.2, area formatting is supported so user can format by column, row, or an area.

**Comment by sillasgonzaga** [comment]
@renkun-ken can you please provide an example of how to do row-wise coloring?
