### ISSUE TITLE
Format column by different column?

### ISSUE THREAD

**Issue by ldecicco-USGS** [renkun-ken/formattable#4]
On your example page, would there be a way to (for example) make all the 27 year old student's names be green? ie.. Can I reference a different column somehow?

**Comment by renkun-ken** [comment]
For now, the following code works:

```r
formattable(df,
  list(name = formatter("span", 
    style = function(x) style(color = ifelse(df$age == 27, "green", NA)))
  ))
```

**Comment by renkun-ken** [comment]
Feel free to reopen the issue if you have questions.
