### ISSUE TITLE
Differences in bar length for same grades

### ISSUE THREAD

**Issue by rdatasculptor** [renkun-ken/formattable#40]
I really enjoy this package! There is only one problem I would like to deal with. Take al look at this screenshot.

![difference in lenghts between same grades](https://cloud.githubusercontent.com/assets/16539796/12215493/566d4b48-b6bf-11e5-8f00-fdd6d1040d22.png)

The two columns show scores with (I pressume) theoretically the same ranges. To my opinion the bar lengths should have the same length when dealing with the same score. As you can see this is not the case with score 9.1. I would like to be able to compare scores in two or more columns 'in one glance'. Because of the different bar lengths this not possible.

Is there way to fix the ranges withing the bar function? Many thanks in advance!

**Comment by renkun-ken** [comment]
One possible solution to this is the following:

```r
formattable(df, list(
  test1_score = formatter("span",
    style = ~ style(
      display = "block",
      width = percent(normalize(c(test1_score, test2_score), min = 0.25)[seq_along(test1_score)]),
      "border-radius" = "4px",
      "padding-right" = "4px",
      "background-color" = "lightpink"
    )),
  test2_score = formatter("span",
    style = ~ style(
      display = "block",
      width = percent(normalize(c(test2_score, test1_score), min = 0.25)[seq_along(test2_score)]),
      "border-radius" = "4px",
      "padding-right" = "4px",
      "background-color" = "lightpink"
    ))
))
```

where `df` is the `data.frame` in the README example. The code uses the syntax `style = ~style()` in `formatter()` to refer to any columns in the `data.frame` which is newly introduced in #34.

**Comment by renkun-ken** [comment]
In v0.2, area formatting is supported so that you can apply formatter function over an area with the same benchmark.
