### ISSUE TITLE
Is it possible to render the bar like styleColorBar in DT package?

### ISSUE THREAD

**Issue by happyshows** [renkun-ken/formattable#42]
Hi,

It seems the bar length is always equal or longer than the length of characters. when comparing with large numbers, the ratio across bars is not displayed proportionately.

see example below: DT vs formattable
![untitled](https://cloud.githubusercontent.com/assets/3208181/12268132/18a5cfde-b911-11e5-8b81-971c5cb20980.png)

**Comment by renkun-ken** [comment]
This may require some re-implementation of the underlying HTML producing mechanism. I'll try to fix this.

**Comment by renkun-ken** [comment]
The latest development version implements `proportion` as #49 suggests. Now you can use `proportion_bar` to do this.
