### ISSUE TITLE
comma() not working for column in DT::datatable within an R Markdown document

### ISSUE THREAD

**Issue by smach** [renkun-ken/formattable#45]
Should this work within an R Markdown document? When I print out the df in the console the Value column has commas, but the column does not have commas within the datatable

    df <- data.frame(Category=c("A", "B", "C"), Value=c(1324, 560, 2000), stringsAsFactors = FALSE)
    df$Value <- formattable::comma(df$Value)
    DT::datatable(df)

**Comment by renkun-ken** [comment]
`formattable(df)` should produce the right output in RMarkdown document. `DT::datatable(df)` might not call `as.character(df$Value)` so that its string representation is not used in the rendered document.

**Comment by smach** [comment]
OK thanks.
