### ISSUE TITLE
color_bar size and alignment

### ISSUE THREAD

**Issue by jtaveras** [renkun-ken/formattable#49]
Hi, discovering this package has made my day / week / month ... thank you!

I've found two issues with color_bar.  Here is the original (ignore the yellow stuff bleeding over from the next column):

![image](https://cloud.githubusercontent.com/assets/1820242/13375492/03489f40-dd6f-11e5-8c84-59110bf029e6.png)

1) normalize creates non-proportional sizes.  E.g., in the table below, it appears the first cell is a tiny fraction of the second, but it really is just half of it.  So the bar should be half as well.

My solution was to override your normalize function and return x / max.

2) When color_bar is really small, it pushes the number right.  My solution was to add a css tag "direction:rtl"

Here is the result

![image](https://cloud.githubusercontent.com/assets/1820242/13375481/d0aaa092-dd6e-11e5-8330-9d2d7da1bd85.png)

**Comment by renkun-ken** [comment]
Thanks for the solution. I'll improve the built-in formatters for such issues.

**Comment by renkun-ken** [comment]
Related to #42.

The update implements `proportion` (suggestion 1). Both `color_bar` and `color_tile` uses `direction:tbl` (suggestion 2).
