### ISSUE TITLE
Set width in knitr?

### ISSUE THREAD

**Issue by sco-lo-digital** [renkun-ken/formattable#50]
Hi,

What a great package!

I see on the cran pdf a couple of ways to set width, but none of them seem to work anymore? 

I just want to set the width for two tables I would like to place side by side in knitr via html.

Thanks
Scott

**Comment by renkun-ken** [comment]
I'm not sure if it is possible with knitr and pandoc. Maybe you can file an issue in knitr or ask a question in stackoverflow?

**Comment by sco-lo-digital** [comment]
Thanks, I posted the question on SO.

http://stackoverflow.com/questions/35922583/setting-the-width-of-formattable-object

**Comment by sco-lo-digital** [comment]
Work around was to use flex dashboard markdown template from RStudio. Thx @renkun-ken @timelyportfolio

**Comment by englianhu** [comment]
https://github.com/renkun-ken/formattable/issues/50#issuecomment-194953506, I tried to applied `formattable`on [Programming Assignment 1 Submission](englianhu.github.io/2016/04/Programming Assignment 1 Submission.html), it became very narrow after I using `htmlwidgets` but horrible wide without it.

**Comment by renkun-ken** [comment]
In v0.2 branch, you can specify the width of the html table via `table_attr` argument but this should not work to place two tables side by side. I recommend that you try [flexdashboard](http://rmarkdown.rstudio.com/flexdashboard/) to make it easier to make documents with layouts.
