### ISSUE TITLE
Changing the css class of the table in Rmarkdown

### ISSUE THREAD

**Issue by diegocgaona** [renkun-ken/formattable#57]
I want to use some css class from Bootstrap in the table from formattable.
Right now, the table have by default `class="table table-condensed"`, and I want to use something like this: `class="table table-condensed table-hover table-striped"`

How can I change this in a formattable to use with Rmarkdown?

Thanks

**Comment by timelyportfolio** [comment]
Just now seeing this.  Not a pretty way, but this accomplishes the task.  I think `formattable` is about to get some helper functionality for this.

```
htmlwidgets::onRender(
  as.htmlwidget(formattable(mtcars)),
'
function(el,x){
  var tbl = el.querySelectorAll("table")[0];
  tbl.className = "table table-condensed table-hover table-striped";
}'
)
```

**Comment by diegocgaona** [comment]
Thanks @timelyportfolio, one more helping me! Your code worked the way I want!

**Comment by renkun-ken** [comment]
In v0.2, `format_table()` has a new argument `table_attr` for user to customize the HTML attributes of the rendered table.
