### ISSUE TITLE
htmlwidget not working with pandoc output

### ISSUE THREAD

**Issue by renkun-ken** [renkun-ken/formattable#6]
If a `formattable data.frame` is rendered to `markdown`, then `htmlwidget` feature would work. However, some table style like `caption` seems unsupported by `markdown` but supported by `pandoc`. If one runs

```r
formattable(head(mtcars), format = "pandoc")
```

Then the resulted `htmlwidget` will be a messy output since pandoc table representation is not recognized by `markdown`. One way to avoid this is to unsupport `pandoc` output in `format_table`. But a minor consequence is that arguments of `knitr::kable` like `caption` will no longer be supported or will be always ignored.

**Comment by timelyportfolio** [comment]
Sorry I missed this functionality.

Would this https://github.com/renkun-ken/formattable/commit/0c6a70c736b76a362cb5cb6b35636726dfa98683 work?  Conversion for `formattable.data.frame` will occur if `is.null(format$format)` implying `"markdown"` or if `format$format == 'markdown'` in case we elect to provide other options for `format$format` down the road.

Also, I wonder should we support `format$format == "htmlwidget"`?

**Comment by renkun-ken** [comment]
A simple way to deal with this is that whenever a `formattable data.frame` is being printed as htmlwidget, its `format` is ignored and always uses `markdown`. But in the rmd-mode, the format works as supposed.

**Comment by timelyportfolio** [comment]
I added the check in an attempt to future-proof the logic.  I can imagine at some point a `format` other than `pandoc` or `markdown` for data.tables that someone might want in an `interactive` context.
