### ISSUE TITLE
Table example from Rmarkdown does not work when package is installed from CRAN

### ISSUE THREAD

**Issue by hilge** [renkun-ken/formattable#62]
You might allready be aware of this issue.
I have no problems running the example if i install with Dev.tools. But when I install the formattable from CRAN I get the following error when running the df table example.

> Error in create_obj(x, "formattable", list(formatter = formatter, format = list(...),  : 
>   could not find function "normalize_bar"

**Comment by renkun-ken** [comment]
In version 0.1.7, `color_bar()` has some breaking changes (see https://github.com/renkun-ken/formattable#breaking-changes). The development version has introduced two new functions as different versions of `color_bar` using different rescaling functions. Unfortunately, CRAN version is not up-to-date yet.
