### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by smmurphy** [renkun-ken/formattable#63]
To start, I love your package!

My question / issue is the way the table width is set. On the current table I am working with the width defaults to 457% with a list of column widths below, several of which exceed 100%.  This renders okay when the table is within a container in an rmarkdown template, however, when I render as an html fragment the percents are taken seriously and push out past the right edge of the screen.  I am using this script to send an HTML email so I am trying to keep dependencies to a minimum.  Is there a better way to render this to control the width?  Set it as fixed, etc.?  Any suggestions would be appreciated.

**Comment by timelyportfolio** [comment]
Hard to answer without any code.  Do you have a minimal example?

**Comment by smmurphy** [comment]
Thanks for the quick response!  Please see the below example.  I have also attached the below .Rmd as a .txt file (since Github won't let me attach the Rmd).  Please let me know if you need any additional information.

## My Rmd file
```
---
title: "Report"
date: "`r format(Sys.time(), '%A, %B %d, %Y, %I:%M %p %Z')`"
output: 
  html_fragment 
---
```
```{r, knitr options, echo= FALSE, message = FALSE, results='hide'} 

# Loads knitr and sets chunk options
library(knitr)
opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, results = 'hide')  
```

```{r}
# Example data
dataOut <- data.frame(
  'Prrty' = rep(c('PROD','HIGH','MED','LOW','TBD','NA'), each =5),
  'Age' = round(runif(30,0,102)),
  'Project' = rep(paste0(letters[1:10], collapse = ""), 30),
  'Description' = rep(paste0(letters, collapse = ""), 30),
  'CrtclDt' = rep(paste0(letters[1:10], collapse = ""), 30),
  'Owner' = rep(paste0(letters[1:4], collapse = ""), 30),
  'ID' = round(runif(30,100,999)),
  'PrjMan' = rep(paste0(letters[1:5], collapse = ""), 30),
  'Status' = rep(paste0(letters[1:5], collapse = ""), 30),
  'Category' = rep(paste0(letters[1:7], collapse = ""), 30),
  'Level' = round(runif(30,1,3)),
  'Reporter'  = rep(paste0(letters[1:4], collapse = ""), 30),
  'StrtDt'  = rep(paste0(letters[1:10], collapse = ""), 30)
)
```


## Some text

```{r results='asis'}
library(formattable)

format_table(dataOut, list(Prrty = formatter(
  "span",
  style = x ~ ifelse(
  x == "PROD",
  style(
  "height:100%; display:block; overflow:auto; background-color: #beaed4"
  ),
  ifelse(
  x == "TBD",
  style(
  "height:100%; display:block; overflow:auto; background-color: #d9d9d9"
  ),
  ifelse(
  x == "LOW",
  style(
  "height:100%; display:block; overflow:auto; background-color: #9ecae1"
  ),
  ifelse(
  x == "MED",
  style(
  "height:100%; display:block; overflow:auto; background-color: #feb24c"
  ),
  ifelse(
  x == "HIGH",
  style(
  "height:100%; display:block; overflow:auto; background-color: #f03b20"
  ),
  NA
  )
  )
  )
  )
  )
  )))
  
```

## Screen shot of the output
![image](https://cloud.githubusercontent.com/assets/7959120/15410866/361f9156-1dea-11e6-89f9-bf98e9b6b060.png)

## HTML responsible for the display
I would like the html widths here to be less than 100% or fixed.

```
<div id="some-text" class="section level2">
<h2>Some text</h2>
<table style="width:306%;">
<colgroup>
<col width="133%"></col>
<col width="6%"></col>
<col width="16%"></col>
<col width="38%"></col>
<col width="16%"></col>
<col width="9%"></col>
<col width="6%"></col>
<col width="11%"></col>
<col width="11%"></col>
<col width="13%"></col>
<col width="9%"></col>
<col width="13%"></col>
<col width="16%"></col>
</colgroup>
```

      
     











[formatTableMWE.txt](https://github.com/renkun-ken/formattable/files/273542/formatTableMWE.txt)

**Comment by timelyportfolio** [comment]
Ok, thanks for the example, and I was able to replicate.  The issue seems to center around `html_fragment`, `knitr`, `rmarkdown`, and not `formattable`.  For instance, change to `html_document`, and everything gets fixed.   I'll troubleshoot more to try to determine what might be happening.

**Comment by smmurphy** [comment]
Thanks so much that seems to solve the problem!  The reason for the requirement is I am sending an alternate version of a report in the body of an email with a more elaborate version attached since JS and other factors were causing some recipients problems when viewed on mobile devices.  Thanks for your help.
