### ISSUE TITLE
make formattable the htmlwidget of the week

### ISSUE THREAD

**Issue by timelyportfolio** [renkun-ken/formattable#7]
Assuming we can work through some of the lingering small issues, I'd like to make `formattable` the new `htmlwidget` of the week especially since it helps illustrate the various contexts in which R might use `html/javascript`.  Would this be ok?

**Comment by renkun-ken** [comment]
That's great!

**Comment by timelyportfolio** [comment]
@renkun-ken not necessary, but I think it would be nice if we could merge this into `master` before a post.  Please let me know your thoughts.

**Comment by renkun-ken** [comment]
We've made some fixes and add some basic tests. If you have no problem, I would like to merge `feature/htmlwidget` into master.

**Comment by timelyportfolio** [comment]
I will try to add a quick vignette also this afternoon and then I will clean up some temp stuff like Readme files

**Comment by timelyportfolio** [comment]
Thanks for merging this.  Look forward to adding some features soon.
