### ISSUE TITLE
[Question] Is it possible to hide a column using the format_table function that is used for a formatter?

### ISSUE THREAD

**Issue by smmurphy** [renkun-ken/formattable#71]
```
f1 <- formatter(
  "span",
  style = ~ ifelse(
  Hours < 1,
  style(
  "height:100%; width:100%; margin: auto; display:block; overflow:auto; background-color: #bdbdbd"
  ),NA
  ))

f2 <- formatter(
  "span",
  style = ~ ifelse(
  CTsk == 'X',
  style(
  "height:100%; width:100%; margin: auto; display:block; overflow:auto; background-color: #fff7bc"
  ),NA
  ))

format_table(projectOut, format="pandoc", list(Quantity = f1, Hours = f1, Task = f2))
```

In the above I would like to use `CTsk` in order to format the table, but not have the column `CTsk` appear in the table.  The above code works fine for the highlighting I want to see. Is it possible to suppress the `CTsk` column with format_table()?

Thanks for your help.

**Comment by the-tourist-** [comment]
Can I second this Issue?  I came here to make the same request, but saw I had been beaten by a week to it.

`
library(formattable)

set.seed(123)
df <- data.frame(result = rnorm(20))
df$p <- pnorm(df$result)

print(formattable(df, list(
  result = formatter("span",
                     style = ~ ifelse(p > 0.9, style(color = "green", font.weight = "bold"), 
                                      ifelse(p < 0.1, style(color = "red", font.weight = "bold"), NA)))
)))
`

**Comment by renkun-ken** [comment]
With 48593ec7a6de43096910a00b542051b76310f7b6, the following code can easily hide a column:

```r
formattable(mtcars, list(mpg = FALSE))
```

**Comment by smmurphy** [comment]
Thanks so much!  Works perfectly.
