### ISSUE TITLE
Docuemntation example using htmlwidget gives error

### ISSUE THREAD

**Issue by andrewrech** [renkun-ken/formattable#74]
Thanks for looking. I get the following error. Package previously worked for me. I tried re-installing and re-install all dependencies from GH or CRAN. I get the same error on OSX and Linux.

```R
devtools::install_github("renkun-ken/formattable")
```

or

```R
install.packages("formattable")
```

```R
library(formattable)

formattable(df, list(
  age = color_tile("white", "orange"),
  grade = formatter("span", style = x ~ ifelse(x == "A", 
  style(color = "green", font.weight = "bold"), NA)),
  area(col = c(test1_score, test2_score)) ~ normalize_bar("pink", 0.2),
  final_score = formatter("span",
  style = x ~ style(color = ifelse(rank(-x) <= 3, "green", "gray")),
  x ~ sprintf("%.2f (rank: %02d)", x, rank(-x))),
  registered = formatter("span",
  style = x ~ style(color = ifelse(x, "green", "red")),
  x ~ icontext(ifelse(x, "ok", "remove"), ifelse(x, "Yes", "No")))
))
```

> debugging in: formattable(df, list(age = color_tile("white", "orange"), grade = formatter("span",
>     style = x ~ ifelse(x == "A", style(color = "green", font.weight = "bold"),
>         NA)), area(col = c(test1_score, test2_score)) ~ normalize_bar("pink",
>     0.2), final_score = formatter("span", style = x ~ style(color = ifelse(rank(-x) <=
>     3, "green", "gray")), x ~ sprintf("%.2f (rank: %02d)", x,
>     rank(-x))), registered = formatter("span", style = x ~ style(color = ifelse(x,
>     "green", "red")), x ~ icontext(ifelse(x, "ok", "remove"),
>     ifelse(x, "Yes", "No")))))
> debug: UseMethod("formattable")
> Browse[2]>
> debugging in: formattable.default(df, list(age = color_tile("white", "orange"),
>     grade = formatter("span", style = x ~ ifelse(x == "A", style(color = "green",
>         font.weight = "bold"), NA)), area(col = c(test1_score,
>         test2_score)) ~ normalize_bar("pink", 0.2), final_score = formatter("span",
>         style = x ~ style(color = ifelse(rank(-x) <= 3, "green",
>             "gray")), x ~ sprintf("%.2f (rank: %02d)", x, rank(-x))),
>     registered = formatter("span", style = x ~ style(color = ifelse(x,
>         "green", "red")), x ~ icontext(ifelse(x, "ok", "remove"),
>         ifelse(x, "Yes", "No")))))
> debug: {
>     create_obj(x, "formattable", list(formatter = formatter,
>         format = list(...), preproc = preproc, postproc = postproc))
> }
> Browse[3]>
> debug: create_obj(x, "formattable", list(formatter = formatter, format = list(...),
>     preproc = preproc, postproc = postproc))
> Browse[3]>
> Error in create_obj(x, "formattable", list(formatter = formatter, format = list(...),  :
>   argument "formatter" is missing, with no default

```R
sessionInfo(package = NULL)
```

> R version 3.3.1 (2016-06-21)
> Platform: x86_64-apple-darwin15.5.0 (64-bit)
> Running under: OS X 10.11.6 (El Capitan)
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base
> 
> other attached packages:
> [1] formattable_0.1.5
> 
> loaded via a namespace (and not attached):
>  [1] shiny_0.13.2    htmlwidgets_0.6 R6_2.1.2        markdown_0.7.7
>  [5] tools_3.3.1     htmltools_0.3.5 parallel_3.3.1  Rcpp_0.12.6
>  [9] knitr_1.13      digest_0.6.9    xtable_1.8-2    httpuv_1.3.3
> [13] mime_0.5

**Comment by timelyportfolio** [comment]
Not on my machine, but try this

```
library(formattable)

formattable(df, formatters=list(
  age = color_tile("white", "orange"),
  grade = formatter("span", style = x ~ ifelse(x == "A", 
  style(color = "green", font.weight = "bold"), NA)),
  area(col = c(test1_score, test2_score)) ~ normalize_bar("pink", 0.2),
  final_score = formatter("span",
  style = x ~ style(color = ifelse(rank(-x) <= 3, "green", "gray")),
  x ~ sprintf("%.2f (rank: %02d)", x, rank(-x))),
  registered = formatter("span",
  style = x ~ style(color = ifelse(x, "green", "red")),
  x ~ icontext(ifelse(x, "ok", "remove"), ifelse(x, "Yes", "No")))
))
```

**Comment by andrewrech** [comment]
Same error. I will dig a bit. Any suggestions? Thanks

**Comment by andrewrech** [comment]
I am confused:

> Browse[3]> ls()
> [1] "formatter" "postproc"  "preproc"   "x"

yet

> Browse[3]> ls.str()
> formatter : \<missing\>
> postproc :  NULL
> preproc :  NULL
> x : function (x, df1, df2, ncp, log = FALSE)

thanks for your help

**Comment by renkun-ken** [comment]
Are you sure to have defined `df` as 

```r
df <- data.frame(
  id = 1:10,
  name = c("Bob", "Ashley", "James", "David", "Jenny", 
    "Hans", "Leo", "John", "Emily", "Lee"), 
  age = c(28, 27, 30, 28, 29, 29, 27, 27, 31, 30),
  grade = c("C", "A", "A", "C", "B", "B", "B", "A", "C", "C"),
  test1_score = c(8.9, 9.5, 9.6, 8.9, 9.1, 9.3, 9.3, 9.9, 8.5, 8.6),
  test2_score = c(9.1, 9.1, 9.2, 9.1, 8.9, 8.5, 9.2, 9.3, 9.1, 8.8),
  final_score = c(9, 9.3, 9.4, 9, 9, 8.9, 9.25, 9.6, 8.8, 8.7),
  registered = c(TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE),
  stringsAsFactors = FALSE)
```

When `df` is not supplied as the data frame above, I'll have the same error.

**Comment by andrewrech** [comment]
Nice! Yes, df was defined as a function from the `stats` package. Thank you so much! Sorry this did not occur to me.
