### ISSUE TITLE
Percent does not work on area() function

### ISSUE THREAD

**Issue by Nicolabo** [renkun-ken/formattable#75]
I try to create a table with percent value using area() function. But actually it does not work at all (i.e. percent value). It seems that code below should work.

```
#library(magrittr)
#library(dplyr)
#library(formattable)
#library(scales)

set.seed(123)
df <- data.frame(id = 1:10, 
             a = rnorm(10), b = rnorm(10), c = rnorm(10))

df <- df %>% 
    mutate(a = percent(a), b = percent(b), c = percent(c))

# show percentage value without using area function
formattable(df, list(a = color_tile("transparent", "pink"),
                     b = color_tile("transparent", "pink"),
                     c = color_tile("transparent", "pink")))

# does not show percentage value
formattable(df, list(area(col = a:c) ~ color_tile("transparent", "pink")))

sessionInfo()

[1] formattable_0.2   DT_0.1            scales_0.4.0 
[4] tidyr_0.4.1       rCharts_0.4.5     dplyr_0.4.3      
[7] shiny_0.13.2     
```

**Comment by renkun-ken** [comment]
The latest version should work.

**Comment by tsvetannikolov** [comment]
When defining a matrix using values that had been processed using the percent function, the percentage signs and the digits limit disappear as well.  I.e. c(conversion.targets$Actualsp[2],conversion.targets$Targetp[2], conversion.targets$cumulativep[2],conversion.targets$cumulativeTp[2]) 
[1] 1.4%  15.0% 1.4%  15.0%

but: 
 steps <- t(matrix(c(Absolute.values$actuals[2],Absolute.values$targets[2],"","",
+                     conversion.targets$Actualsp[2],conversion.targets$Targetp[2], conversion.targets$cumulativep[2],conversion.targets$cumulativeTp[2]), nrow=4, ncol=2))

              [,1]                 [,2]     [,3]                 [,4]         
 [1,] "2325"               "12038"  ""                   ""           
 [2,] "0.0137634408602151" "0.15"   "0.0137634408602151" "0.15"
