### ISSUE TITLE
Hide column headers

### ISSUE THREAD

**Issue by dmklotz** [renkun-ken/formattable#90]
Is there a way to display a column, but hide the column names in the header?  Assigning blank values to the column names in the original dataframe won't work.  

Essentially, I want to use color_bar with the values beside the bar.  I can do this by replicating columns, and displaying one regularly and another with color_bar, but then I have double column names.  Perhaps this is a better way to do this?

Thanks!

**Comment by BertWassink** [comment]
Add a css snippet 

```{r results="asis", echo=FALSE}
cat("
<style>

th {
 border: none;
 display: none;
}

</style>
")
```

**Comment by mikedolanfliss** [comment]
I'm following this, and a little confused. #57 gave us table.attr - is that the right way to ingest this overall css? I haven't seen table.attr used yet in practice (like in the format_table examples, where I think it'd be great), so am having a hard time wrapping my head.

**Comment by dmklotz** [comment]
I don't understand where to define CSS snippets in formattable either.  

Instead, I found a simple workaround using HTML.  Instead of a blank character in R, one can use the HTML non-breaking space entity as a column name.  The column names still need to unique, so the following works for me:

blank_column_1 <- "&nbsp"
blank_column_2 <- "&nbsp&nbsp"
etc.
